<?php

/**
 * Digit Software Solutions.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category  Dss
 * @package   Dss_Opinion
 * @author    Extension Team
 * @copyright Copyright (c) 2025 Digit Software Solutions. ( https://digitsoftsol.com )
 */

/** @var \Dss\Opinion\Block\MyOpinions $block */
$customerOpinions = $block->getCustomerOpinions();
?>
<?php if (!$block->canCustomerGiveOpinion()): ?>
    <?php if ($block->getDisallowedCustomerMessage()): ?>
        <div class="message error empty disallowed-customer">
            <div>
                <?= /* @noEscape */ __($block->getDisallowedCustomerMessage()) ?>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
<?php if ($customerOpinions->getSize()): ?>
    <div class="table-wrapper customer-opinions">
        <table class="data table table-opinion-items" id="my-opinions-table">
            <caption class="table-caption"><?= $escaper->escapeHtml(__('My Product Opinions')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col product-image"><?= $escaper->escapeHtml(__('Product Image')) ?></th>
                    <th scope="col" class="col product-name"><?= $escaper->escapeHtml(__('Product Name')) ?></th>
                    <th scope="col" class="col product-opinion"><?= $escaper->escapeHtml(__('Product Opinion')) ?></th>
                </tr>
            </thead>
            <tbody id="opinions-list">
                <?php foreach ($customerOpinions as $opinion): ?>
                    <?php $product = $block->getProductById($opinion->getProductId()); ?>
                    <?php if ($product): ?>
                        <?php
                            $productImage = $block->getImageUrl($product);
                            $opinionClass = $opinion->getOpinion() == 1 ? 'liked' : 'disliked';
                        ?>
                        <tr>
                            <td data-th="<?= $escaper->escapeHtml(__('Product Image')) ?>"
                                class="col product-image <?= $escaper->escapeHtml(__($opinionClass)) ?>">
                                <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                                    <img src="<?= $escaper->escapeUrl($productImage) ?>"
                                        alt="<?= $escaper->escapeHtml($product->getName()) ?>" width="50" height="50" />
                                </a>
                            </td>
                            <td data-th="<?= $escaper->escapeHtml(__('Product Name')) ?>"
                                class="col product-name <?= $escaper->escapeHtml(__($opinionClass)) ?>">
                                <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                                    <?= $escaper->escapeHtml($product->getName()) ?>
                                </a>
                            </td>
                            <td data-th="<?= $escaper->escapeHtml(__('Product Opinion')) ?>"
                                class="col product-opinion <?= $escaper->escapeHtml(__($opinionClass)) ?>">
                                <?= $escaper->escapeHtml($opinion->getOpinion() == 1 ? __('Liked') : __('Disliked')) ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="product-opinion-pager toolbar bottom">
            <?= $block->getPagerHtml() ?>
        </div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty">
        <span><?= $escaper->escapeHtml(__('You have not given any opinions yet.')) ?></span>
    </div>
<?php endif; ?>