<?php

/**
 * Digit Software Solutions.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category  Dss
 * @package   Dss_Opinion
 * @author    Extension Team
 * @copyright Copyright (c) 2025 Digit Software Solutions. ( https://digitsoftsol.com )
 */

/** @var \Dss\Opinion\Block\MyOpinions $block */
$customerOpinions = $block->getCustomerOpinions();
$query = $block->getRequest()->getParam('opinion_query');
$queryProductIds = $block->getRequest()->getParam('product_ids');
?>

<div class="dss-customer-opinions">
    <?php if (!$block->canCustomerGiveOpinion() && $block->getDisallowedCustomerMessage()): ?>
            <div class="message error empty disallowed-customer">
                <div>
                    <?= $escaper->escapeHtml(__($block->getDisallowedCustomerMessage())) ?>
                </div>
            </div>
    <?php else: ?>
        <?php if (!$block->isOpinionSubmissionAllowed() && $block->getOpinionDisabledMessage()): ?>
            <div class="message info empty disable-message">
                <div>
                    <?= $escaper->escapeHtml(__($block->getOpinionDisabledMessage())) ?>
                </div>
            </div>
        <?php endif; ?>
    <?php endif; ?>
    <?php if ($customerOpinions->getSize()): ?>
        <div class="opinion-search">
            <form method="get" id="opinion-search-form" class="opinion-search-form" action="">
                <div class="suggestion-wrapper">
                    <input type="text"
                           class="opinion-search-input"
                           id="opinion-search-input"
                           name="opinion_query"
                           autocomplete="off"
                           placeholder="Search opinion by product name..."
                           value="<?= $escaper->escapeHtml($query) ?>"
                           data-mage-init='{"Dss_Opinion/js/autosuggest": {}}' />

                    <input type="hidden"
                           name="product_ids"
                           id="product_ids_input"
                           value="<?= $escaper->escapeHtml($queryProductIds) ?>" />

                    <ul id="opinion-suggestions" class="suggestion-list" style="display: none;"></ul>
                </div>
                <button type="submit" class="action primary search-button" title="Search">
                    <?= $escaper->escapeHtml(__('Search')) ?>
                </button>
            </form>
            <?php $query = $block->getSearchQuery(); ?>
            <?php if ($block->isTooShortQuery()): ?>
                <div class="message info too-short">
                    <div>
                        <?= $escaper->escapeHtml(__(
                            'Search term too short — need at least 3 characters to show product opinions.'
                        )) ?>
                    </div>
                </div>
            <?php elseif ($block->hasNoProductMatch()): ?>
                <div class="message info not-found">
                    <div>
                        <?= $escaper->escapeHtml(__(
                            'Sorry, no opinions were found for products matching "%1". Here are all your opinions.',
                            $query
                        )) ?>
                    </div>
                </div>
            <?php elseif ($block->getMatchedOpinionCount() > 0): ?>
                <div class="message success opinion-found">
                    <div>
                        <?= $escaper->escapeHtml(__(
                            'Great! You’ve shared %1 opinion(s) for product matching "%2".',
                            $block->getMatchedOpinionCount(),
                            $query
                        )) ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <?php if ($block->isOpinionChartEnabled() || $block->isCurrentOpinionChartEnabled()): ?>
            <div class="opinion-stats" data-mage-init='{"Dss_Opinion/js/chart-type-selector":{}}'>
                <div class="charts-wrapper">
                    <?= $block->getChildHtml('customer_product_opinion_charts') ?>
                </div>
            </div>
        <?php endif; ?>
        <div class="table-wrapper customer-opinions">
            <table class="data table table-opinion-items" id="my-opinions-table">
                <caption class="table-caption"><?= $escaper->escapeHtml(__('My Product Opinions')) ?></caption>
                <thead>
                    <tr>
                        <th scope="col" class="col product-image">
                            <?= $escaper->escapeHtml(__('Product Image')) ?>
                        </th>
                        <th scope="col" class="col product-name">
                            <?= $escaper->escapeHtml(__('Product Name')) ?>
                        </th>
                        <th scope="col" class="col product-opinion">
                            <?= $escaper->escapeHtml(__('Product Opinion')) ?>
                        </th>
                        <?php if ($block->canCustomerGiveOpinion() && $block->isOpinionSubmissionAllowed()): ?>
                            <th scope="col" class="col product-opinion-actions">
                                <?= $escaper->escapeHtml(__('Actions')) ?>
                            </th>
                        <?php endif; ?>
                    </tr>
                </thead>
                <tbody id="opinions-list">
                    <?php foreach ($customerOpinions as $opinion): ?>
                        <?php $product = $block->getProductById($opinion->getProductId()); ?>
                        <?php if ($product): ?>
                            <?php
                                $productImage = $block->getImageUrl($product);
                                $opinionClass = $opinion->getOpinion() == 1 ? 'liked' : 'disliked';
                            ?>
                            <tr>
                                <td data-th="<?= $escaper->escapeHtml(__('Product Image')) ?>"
                                    class="col product-image <?= $escaper->escapeHtml(__($opinionClass)) ?>">
                                    <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                                        <img src="<?= $escaper->escapeUrl($productImage) ?>"
                                            alt="<?= $escaper->escapeHtml($product->getName()) ?>"
                                            width="75"
                                            height="75"
                                            loading="lazy"
                                            class="opinion-product-image" />
                                    </a>
                                </td>
                                <td data-th="<?= $escaper->escapeHtml(__('Product Name')) ?>"
                                    class="col product-name <?= $escaper->escapeHtml(__($opinionClass)) ?>">
                                    <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                                        <?= $escaper->escapeHtml($product->getName()) ?>
                                    </a>
                                </td>
                                <?php $opinionText = $opinion->getOpinion() == 1 ? __('Liked') : __('Disliked'); ?>
                                <td data-th="<?= $escaper->escapeHtml(__('Product Opinion')) ?>"
                                    class="col product-opinion <?= $escaper->escapeHtml(__($opinionClass)) ?>">
                                    <?= $escaper->escapeHtml($opinionText) ?>
                                </td>
                                <?php
                                    $opinionId = $opinion->getCustomerOpinionId();
                                    $formKey = $block->getFormKey();
                                    $productId = $opinion->getProductId();
                                    $productName = $product->getName();
                                    $currentOpinion = $opinion->getOpinion();
                                    $newOpinion = $currentOpinion == 1 ? 0 : 1;
                                    $actionLabel = $newOpinion == 1 ? __('Change to Like') : __('Change to Dislike');
                                    $newOpinionId = $newOpinion == 1 ? 'like-button' : 'dislike-button';
                                    $buttonClass = $newOpinion == 1 ? 'primary' : 'secondary';
                                    $newOpinionClass = $newOpinion == 1 ? 'liked' : 'disliked';
                                ?>
                                <?php if ($block->canCustomerGiveOpinion() && $block->isOpinionSubmissionAllowed()): ?>
                                    <td data-th="<?= $escaper->escapeHtml(__('Actions')) ?>"
                                        class="col product-opinion-actions
                                            <?= $escaper->escapeHtml(__($opinionClass)) ?>"
                                        id="opinion-actions-<?= $escaper->escapeHtml(__($opinionId)) ?>">
                                        <div class="actions-btns">
                                            <button type="button"
                                                    class="action <?= $escaper->escapeHtml(__($buttonClass)) ?>
                                                        change-opinion <?= $escaper->escapeHtml(__($opinionClass)) ?>"
                                                    id="<?= $escaper->escapeHtml(__($newOpinionId)) ?>"
                                                    data-opinion="<?= $escaper->escapeHtml(__($newOpinion)) ?>">
                                                <?= $escaper->escapeHtml(__($actionLabel)) ?>
                                            </button>
                                            <button type="button"
                                                    class="action delete-opinion"
                                                    id="delete-<?= $escaper->escapeHtml(__($opinionId)) ?>"
                                                    data-opinion-id="<?= $escaper->escapeHtml($opinionId) ?>">
                                                <?= $escaper->escapeHtml(__('Delete')) ?>
                                            </button>
                                        </div>
                                    </td>
                                <?php endif; ?>
                            </tr>

                            <?php if ($block->canCustomerGiveOpinion() && $block->isOpinionSubmissionAllowed()): ?>
                                <script type="text/x-magento-init">
                                    {
                                        "*": {
                                            "opinionActions": {
                                                "elementId": "opinion-actions-<?= $escaper->escapeJs($opinionId) ?>",
                                                "opinionId": "<?= $escaper->escapeJs($opinionId) ?>",
                                                "formKey": "<?= $escaper->escapeJs($formKey) ?>",
                                                "productId": "<?= $escaper->escapeJs($productId) ?>",
                                                "productName": "<?= $escaper->escapeJs($productName) ?>",
                                                "errorMessage": "<?= $escaper->escapeJs(__('Something went wrong.')) ?>"
                                            }
                                        }
                                    }
                                </script>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="product-opinion-pager toolbar bottom">
                <?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
    <?php else: ?>
        <div class="message info empty">
            <span><?= $escaper->escapeHtml(__('You have not given any opinions yet.')) ?></span>
        </div>
    <?php endif; ?>
</div>