<?php

/**
 * Digit Software Solutions.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category  Dss
 * @package   Dss_Opinion
 * @author    Extension Team
 * @copyright Copyright (c) 2025 Digit Software Solutions. ( https://digitsoftsol.com )
 */

/** @var \Dss\Opinion\Block\ProductOpinionLabel $block */
$product = $block->getLayout()->getBlock('product.info')->getProduct();
$productId = $product ? $product->getId() : 0;
?>

<?php if ($block->isOpinionLabelEnabled() && $block->isProductOpinionEnabled()): ?>
    <div class="product-opinion-label" id="product-opinion-label" style="display: none;"></div>

    <script type="text/x-magento-init">
        {
            "#product-opinion-label": {
                "productOpinionLabel": {
                    "labelUrl": "<?= /* @noEscape */ $block->getAjaxUrl() ?>",
                    "productId": "<?= /* @noEscape */ (int) $productId ?>"
                }
            }
        }
    </script>
<?php endif; ?>